version: '3.1'

services:
  jupyter:
    image: jupyter/tensorflow-notebook:tensorflow-2.9.1
    container_name: tensorflow_notebook
    environment:
      NB_GID: 109
    user: root
    volumes:
      - ./jupyter:/home/jovyan
    ports:
      - 8888:8888/tcp

